dovecot_config_version = 2.4.3
dovecot_storage_version = 2.4.3

mail_path = ~/mail
mail_home = /var/mail/%{user}
mail_driver = mbox

mail_driver = mbox
mail_path = /home/%{user}/mail
mail_home = /home/%{user}/mail
mail_inbox_path = /var/mail/%{user}

auth_verbose = no

mail_uid = %{user}
mail_gid = mail

protocols = imap pop3
auth_mechanisms = plain
mail_privileged_group = mail
passdb pam {
  service_name = dovecot
}
service auth-worker {
  group = shadow
  user = root
}
service auth {
  unix_listener /var/lib/postfix/private/auth {
    mode = 0660
    # Assuming the default Postfix user and group
    user = postfix
    group = postfix
  }
}

ssl = yes

ssl_server {
  key_file = /etc/dovecot/pointless-dovecot.key
  cert_file = /etc/dovecot/pointless-dovecot.crt
}

default_login_user = dovenull
default_internal_user = dovecot
mail_plugins = ssl_iostream_openssl
