#!/usr/bin/env bash

export PATH="$PATH:$HOME/tools/bin/"
export LOCALE_ARCHIVE="$HOME/tools/lib/locale/locale-archive"

cutoffdate="$1"
ts="$(date --date="$cutoffdate" +%s)"

tsre="$ts"

l="${#ts}"

while test "$l" -gt 1; do
        l=$((l-1))
        last="${ts:l:1}"
        prefix="${ts:0:l}"
        tsre="$tsre|($prefix[$last-9][0-9]*)"
done

cutoff="$cutyear-$cutmonth-(${cutday:0:1}[${cutday:1:1}-9]|[$((${cutday:0:1} + 1))-9].)"

trap "reset; exit" 3

while ( grep -A999999 -E "^($tsre) " ~/mnt/irc/irc.freenode.net/*/out | sed -re 's@^([-/a-z.0-9#]*/out:[0-9]{6})[0-9]{4} -!- .*@\10000@' | uniq  | less -c ); do :; done;
