#!/bin/sh

export HOME=/home/raskin
export PATH="$PATH:$HOME/tools/bin/"
export IRC_SERVER=irc.libera.chat
export CHANNELS='nixos-security stumpwm irp tunes bussard ca-duel cl-fuse query-fs nixos-de spectrum'

check_running(){
        ps -ef | grep -v grep | grep " ii -s $IRC_SERVER " > /dev/null
}

while true; do
        while check_running; do
                sleep 1;
        done;
        rm ~/mnt/irc/"$IRC_SERVER"/in
        ii -s "$IRC_SERVER" -i ~/mnt/irc/ -n IdleBot_$(
                        dd if=/dev/urandom bs=1 count=4 | xxd -ps ) &
        while ! test -e  ~/mnt/irc/"$IRC_SERVER"/in; do
                sleep 1;
                check_running || exit 1
        done
        for c in $CHANNELS; do
                echo /j "#$c" > ~/mnt/irc/"$IRC_SERVER"/in;
                sleep 1;
        done;
done
