# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "bindings-1.2.1" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz";
        sha1 = "14ad6113812d2d37d72e67b4cacb4bb726505f11";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "ffi-2.2.0" = {
      name = "ffi";
      packageName = "ffi";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ffi/-/ffi-2.2.0.tgz";
        sha1 = "bf18b04666a29f71227ed56895d5430af47042fa";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "nan-2.11.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.11.0.tgz";
        sha512 = "F4miItu2rGnV2ySkXOQoA8FKz/SR2Q2sWP0sbTxNxz/tuokeC8WxOhPMcwi0qIyGtVn/rrSeLbvVkznqCdwYnw==";
      };
    };
    "ref-1.3.5" = {
      name = "ref";
      packageName = "ref";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ref/-/ref-1.3.5.tgz";
        sha512 = "2cBCniTtxcGUjDpvFfVpw323a83/0RLSGJJY5l5lcomZWhYpU2cuLdsvYqMixvsdLJ9+sTdzEkju8J8ZHDM2nA==";
      };
    };
    "ref-struct-1.1.0" = {
      name = "ref-struct";
      packageName = "ref-struct";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ref-struct/-/ref-struct-1.1.0.tgz";
        sha1 = "5d5ee65ad41cefc3a5c5feb40587261e479edc13";
      };
    };
    "ref-union-1.0.1" = {
      name = "ref-union";
      packageName = "ref-union";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ref-union/-/ref-union-1.0.1.tgz";
        sha1 = "3a2397f862f1e75171d687268f43b3f17729f120";
      };
    };
    "semver-5.5.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.5.1.tgz";
        sha512 = "PqpAxfrEhlSUWge8dwIp4tZnQ25DIOthpiaHNIthsjEFQD6EvqUKUDM7L8O2rShkFccYo1VjJR0coWfNkCubRw==";
      };
    };
  };
  args = {
    name = "purple";
    packageName = "purple";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."bindings-1.2.1"
      sources."debug-2.6.9"
      sources."ffi-2.2.0"
      sources."ms-2.0.0"
      sources."nan-2.11.0"
      sources."ref-1.3.5"
      sources."ref-struct-1.1.0"
      sources."ref-union-1.0.1"
      sources."semver-5.5.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "libpurple FFI Bindings";
      homepage = http://github.com/tjfontaine/node-purple;
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}